
export const ActionType = {
    PLAYING: 'PLAYING',
    ATTACKING: 'ATTACKING',
    DEFENDING: 'DEFENDING',
    FEAR: 'FEAR',
    HUNGER: 'HUNGER',
    THIRST: 'THIRST',
    IDLE: 'IDLE',
    INTERACTING: 'INTERACTING'
}